**What is NumPy?**

NumPy (Numerical Python) is a Python library used for numerical computing.

It provides a powerful data structure called the NumPy array, which allows us to store and perform operations on large amounts of numerical data efficiently.

**Why do we need NumPy?**

Suppose you have 1 million numbers and want to:

-Add 10 to every number

-Calculate the average

-Perform matrix multiplication

-Process image pixels

-Prepare data for Machine Learning

Python lists can do some of these tasks, but NumPy arrays are designed specifically for numerical operations and are generally more efficient and convenient.


**Python List vs NumPy Array**

Important: NumPy is not simply a faster list. It is an array-computing system with specialized operations, data types, and memory behavior.

In [ ]:
# Python List
numbers=[1,2,3,4,5,6]
result=[]
for num in numbers:
    result.append(num+10)
print(result)

[11, 12, 13, 14, 15, 16]


In [2]:
# Numpy Array
import numpy as np
numbers=np.array([1,2,3,4,5,6])
result=numbers+10
print(result)

[11 12 13 14 15 16]


**NumPy's Role in Data Science and ML**

NumPy is a foundation for many Python data science libraries.

-> Data Science

Numerical calculations, data manipulation, statistics, and preprocessing.

-> Machine Learning

Feature matrices, mathematical operations, normalization, and algorithm implementation.

-> Deep Learning

Numerical arrays are the conceptual foundation for tensors used in neural networks.

In [3]:
# Example : Dataset in ML
X = np.array([
    [22, 25000, 1],
    [25, 40000, 3],
    [30, 60000, 6]
])
print(X)   #can be represent like this

[[   22 25000     1]
 [   25 40000     3]
 [   30 60000     6]]


**What is Vectorization?**

Vectorization means performing an operation on an entire array instead of manually processing each element using a Python loop.

__Why is vectorization important?__

NumPy performs many array operations using optimized compiled code internally, reducing the need for Python-level loops.

In [4]:
# Without Vectorization
numbers = [1, 2, 3, 4, 5]
result = []
for num in numbers:
    result.append(num * 2)
print(result)

[2, 4, 6, 8, 10]


In [5]:
# With Vectorization
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
result = numbers * 2
print(result) 

[ 2  4  6  8 10]


**First NumPy Program**

In [6]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers)
print(numbers + 5)
print(numbers * 2)
print(numbers.mean())

[10 20 30 40 50]
[15 25 35 45 55]
[ 20  40  60  80 100]
30.0


**Installing and Importing NumPy**

This topic is simple, but you should understand how to set up NumPy correctly before using it.

In [ ]:
# Installing NumPy

#If NumPy is not installed, open your terminal or command prompt and run:
#   pip install numpy

#If you are using a Jupyter Notebook, you can run:
#   %pip install numpy

#If you use uv
#Since you have used uv in your Python projects, you can install NumPy in a project using:
#   uv add numpy

In [7]:
# Checking version of Numpy
import numpy as np
print(np.__version__)

1.26.4


**Creating NumPy Arrays**

This is one of the most important topics in NumPy. Almost everything you do with NumPy starts with creating an array.

**What is a NumPy Array?**

A NumPy array is a collection of elements stored in a structured, multidimensional format.

NumPy's array object is called an ndarray, which means n-dimensional array.

In [ ]:
# Creating a 1D Array
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [10]:
# Creating a 2D Array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# Creating a 3D Array
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Mixed Data Types in Arrays**

NumPy generally tries to use a common data type for all elements.

In [12]:
arr = np.array([1, 2.5, 3])
print(arr)
print(arr.dtype)

[1.  2.5 3. ]
float64


**Array Attributes**

Array attributes help you understand the structure, size, and data type of a NumPy array. These are used frequently when working with datasets, images, and ML models.

In [13]:
# ndim - Numbers of Dimension
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr.ndim)

2


In [14]:
# shape — Size Along Each Dimension
print(arr.shape)

(2, 3)


In [15]:
# size — Total Number of Elements
print(arr.size)

6


In [16]:
# dtype — Data Type
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [18]:
# itemsize — Bytes Per Element
# nbytes - Total Used Bytes
arr = np.array([1, 2, 3, 4])
print(arr.itemsize)  
print(arr.nbytes)

8
32


**NumPy Data Types**

NumPy arrays store data using a specific data type, called dtype. Understanding data types is important because they affect how values are stored, how operations work, and how much memory an array uses.

**Common NumPy Data Types**

Data type->Meaning->Example

int32 / int64->Integer->10

float32 / float64->Decimal number->10.5

bool->True or False->True

str_->String->"hello"

In [ ]:
#NumPy automatically determines a suitable data type when you create an array.

arr = np.array([10, 20, 30])
print(arr.dtype)

arr = np.array([10.5, 20.5, 30.5])
print(arr.dtype)

int64
float64


In [20]:
# Specifying a Data Type
# You can explicitly specify the data type using dtype.
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float32


In [21]:
# Boolean Arrays
arr = np.array([True, False, True, True])
print(arr)
print(arr.dtype)

[ True False  True  True]
bool


In [ ]:
# astype() — Converting Data Types
# astype() generally returns a new array rather than changing the original array in place.
arr = np.array([1, 2, 3])
new_arr = arr.astype(float)
print(new_arr)
print(new_arr.dtype)

[1. 2. 3.]
float64


**Creating Arrays Using Built-in Functions**

NumPy provides functions to create arrays quickly without manually writing every element. These are especially useful for initializing datasets, matrices, and numerical computations.

In [24]:
# np.zeros() -> Creates an array filled with zeros.
arr = np.zeros(5)
print(arr)

arr = np.zeros((2, 3))
print(arr)

arr = np.zeros(5, dtype=int)
print(arr)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 0 0 0 0]


In [25]:
# np.ones() -> Creates an array filled with ones.
arr = np.ones((2, 3))
print(arr)

arr = np.ones(4, dtype=int)
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]
[1 1 1 1]


In [26]:
# np.full() -> Creates an array where every element has the same specified value.
arr = np.full((2, 3), 7)
print(arr)

arr = np.full(5, 100)
print(arr)

[[7 7 7]
 [7 7 7]]
[100 100 100 100 100]


In [27]:
# np.empty() — Basic Awareness
#np.empty() creates an array without initializing its elements to a specific value.
arr = np.empty(5)
print(arr)

[0. 0. 0. 0. 0.]


In [28]:
# np.eye() -> Creates an identity matrix: ones on the main diagonal and zeros elsewhere.
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# np.arange()-> Creates an array of evenly spaced values within a specified range.
arr = np.arange(1, 10)
print(arr)

#with step
arr = np.arange(1, 10)
print(arr)

arr = np.arange(10, 0, -2)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[10  8  6  4  2]


In [30]:
# np.linspace() -> Creates a specified number of evenly spaced values between two endpoints.
arr = np.linspace(0, 10, 5)
print(arr)

arr = np.linspace(0, 1, 6)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
[0.  0.2 0.4 0.6 0.8 1. ]


**Basic Array Operations**

NumPy allows you to perform mathematical operations directly on arrays. These operations are usually element-wise, meaning the operation is applied to each corresponding element.

In [31]:
# Creating Two Arrays
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

In [33]:
# Addition and Subtraction -> The corresponding elements are added or subtracted.
print(a + b)
print(a - b)

#Multiplication and Division
print(a * b)
print(a / b)

[12 24 35]
[ 8 16 25]
[ 20  80 150]
[5. 5. 6.]


In [34]:
# Scalar Operations -> A scalar is a single value. NumPy can apply a scalar operation to every element of an array.
a = np.array([10, 20, 30])
print(a + 5)
print(a - 5)
print(a * 2)
print(a / 10)

[15 25 35]
[ 5 15 25]
[20 40 60]
[1. 2. 3.]


In [35]:
# Power and Modulus -> These are also useful basic operations.
a = np.array([1, 2, 3, 4])
print(a ** 2)
print(a % 2)

[ 1  4  9 16]
[1 0 1 0]


In [37]:
#Comparison Operators -> Comparisons produce a Boolean array containing True or False for each element.
a = np.array([10, 20, 30, 40])
print(a > 20)
print(a == 20)
print(a != 20)
print(a < 30)
print(a >= 30)
print(a <= 20)

[False False  True  True]
[False  True False False]
[ True False  True  True]
[ True  True False False]
[False False  True  True]
[ True  True False False]


In [38]:
#Comparing Two Arrays -> You can compare corresponding elements of two arrays.
a = np.array([10, 20, 30])
b = np.array([15, 20, 25])
print(a > b)

[False False  True]


In [41]:
#Important: Array Operations vs Matrix Operations
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# * multiplies corresponding elements. 
print(A * B)

# @ performs matrix multiplication.
print(A @ B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
