In [2]:
import numpy as np

**Indexing**

Indexing means accessing individual elements from an array.

Python and NumPy use zero-based indexing, meaning the first element is at index 0.

In [4]:
# 1D Array Indexing
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[2])
print(arr[-1])  # Last element
print(arr[-2])  # Second-last element

#Modifying an Element
arr[1] = 25
print(arr)

10
30
50
40
[10 25 30 40 50]


In [5]:
# 2D Array Indexing
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0, 0])  # 10
print(arr[1, 2])  # 60

# Accessing an Entire Row
print(arr[0])

# Accessing an Entire Column
print(arr[:, 0])

# Modifying a 2D Element
arr[1, 1] = 500
print(arr)

10
60
[10 20 30]
[10 40 70]
[[ 10  20  30]
 [ 40 500  60]
 [ 70  80  90]]


In [6]:
# 3D Array Indexing
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(arr.shape)

#Accessing Elements
print(arr[0, 0, 0])  # 1
print(arr[1, 0, 1])  # 8

# Accessing a 2D Block
print(arr[0])

(2, 2, 3)
1
8
[[1 2 3]
 [4 5 6]]


**Slicing**

Slicing is used to select a range of elements from an array without accessing each element individually.

In [7]:
# 1D Array Slicing
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4])

#From the Beginning
print(arr[:3])

# Until the End
print(arr[3:])

#Using a Step
print(arr[::2])

# Reverse an Array
print(arr[::-1])

#Modifying Values Using Slicing
arr[1:4] = 100
print(arr)

# You can also assign different values:
arr[1:4] = [200, 300, 400]
print(arr)

[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]
[60 50 40 30 20 10]
[ 10 100 100 100  50  60]
[ 10 200 300 400  50  60]


In [8]:
# 2D Array Slicing
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

#First Two Rows
print(arr[:2])

#Last Two Rows
print(arr[1:])

# Selecting Every Second Row
print(arr[::2])

#First Two Columns
print(arr[:, :2])

#Last Two Columns
print(arr[:, 2:])

#Selecting One Column
print(arr[:, 1])

#Selecting Multiple Specific Columns Through Slicing
print(arr[:, ::2])

# Selecting a Subarray
sub = arr[0:2, 1:3]
print(sub)

[[10 20 30 40]
 [50 60 70 80]]
[[ 50  60  70  80]
 [ 90 100 110 120]]
[[ 10  20  30  40]
 [ 90 100 110 120]]
[[ 10  20]
 [ 50  60]
 [ 90 100]]
[[ 30  40]
 [ 70  80]
 [110 120]]
[ 20  60 100]
[[ 10  30]
 [ 50  70]
 [ 90 110]]
[[20 30]
 [60 70]]


In [10]:
# Slicing with Negative Indexing
arr = np.array([10, 20, 30, 40, 50, 60])

#Last Three Elements
print(arr[-3:])

#Excluding the Last Element
print(arr[:-1])

#Reverse the Last Three Elements
print(arr[-1:-4:-1])

[40 50 60]
[10 20 30 40 50]
[60 50 40]


In [ ]:
#  View vs Copy
#A basic NumPy slice usually creates a view of the original array rather than a completely independent copy.
arr = np.array([10, 20, 30, 40])

part = arr[1:3]
part[0] = 999
print(arr)

#To create an independent copy:
part = arr[1:3].copy()

**To create an independent copy:**

Boolean indexing is used to filter values based on conditions. It is commonly used in data cleaning, preprocessing, and selecting specific data points in machine learning.

In [13]:
#Filtering Values Using a Condition
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr > 30)

#To get the actual values:
print(arr[arr > 30])

#Values Less Than 40
print(arr[arr != 30])

#Values Equal to 30
print(arr[arr == 30])

#Values Not Equal to 30
print(arr[arr != 30])

#Values Greater Than or Equal to 40
print(arr[arr >= 40])

# AND Condition -> Select values greater than 20 and less than 60.
print(arr[(arr > 20) & (arr < 60)])

# OR Condition -> Select values less than 20 or greater than 50.
print(arr[(arr < 20) | (arr > 50)])

# NOT Condition -> Select values that are not greater than 30.
print(arr[~(arr > 30)])

[False False False  True  True  True]
[40 50 60]
[10 20 40 50 60]
[30]
[10 20 40 50 60]
[40 50 60]
[30 40 50]
[10 60]
[10 20 30]


In [15]:
#Boolean Indexing in 2D Arrays
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

#Select All Values Greater Than 50
print(arr[arr > 50])

# Replace Values Based on a Condition -> You can directly modify values that satisfy a condition.
arr[arr > 50] = 0
print(arr)

[60 70 80 90]
[[10 20 30]
 [40 50  0]
 [ 0  0  0]]


In [16]:
# np.where() Basic Awareness -> np.where() can be used to select or replace values based on a condition.
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 30, 0, arr)
print(result)

[10 20 30  0  0]


**Fancy Indexing**

Fancy indexing allows you to select multiple specific elements, rows, or columns using an array or list of indices.

In [18]:
# Fancy Indexing in 1D Arrays
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[[0, 2, 5]])

# Select Elements in a Different Order
print(arr[[4, 1, 3]])

[10 30 60]
[50 20 40]


In [20]:
# Fancy Indexing in 2D Arrays
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

# Select Specific Rows
print(arr[[0, 2]])

#Select Rows in a Different Order
print(arr[[3, 1]])

#Selecting Specific Columns -> To select specific columns, use slicing for rows and a list of column indices.
print(arr[:, [0, 2]])

#Select Columns in a Different Order
print(arr[:, [2, 0]])

#Selecting Specific Rows and Columns Together
rows = [0, 2, 3]
cols = [1, 2, 0]
print(arr[rows, cols])

[[10 20 30]
 [70 80 90]]
[[100 110 120]
 [ 40  50  60]]
[[ 10  30]
 [ 40  60]
 [ 70  90]
 [100 120]]
[[ 30  10]
 [ 60  40]
 [ 90  70]
 [120 100]]
[ 20  90 100]


In [ ]:
#Fancy Indexing for Updating Values -> You can also modify multiple selected elements.
arr = np.array([10, 20, 30, 40, 50, 60])
arr[[1, 3, 5]] = 0
print(arr)

# you can assign different values
arr[[0, 2, 4]] = [100, 200, 300]
print(arr)

[10  0 30  0 50  0]


**Changing Array Shape**

Array shape manipulation changes how data is arranged without necessarily changing the actual values.

This is especially important in machine learning, where models expect data in a specific shape.

In [22]:
#reshape() -> reshape() changes the dimensions of an array while keeping the same elements.

# 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

#Using -1 -> NumPy can automatically calculate one dimension using -1.
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(2, -1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [23]:
#flatten() ->  flatten() converts a multidimensional array into a 1D array.
#flatten() returns a copy of the array.
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [24]:
#ravel()  ->  ravel() also converts an array into 1D.
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
result = arr.ravel()
print(result)

[1 2 3 4 5 6]


In [25]:
#flatten() when you need an independent copy.
#ravel() when you want efficient flattening and do not need a guaranteed copy.

In [26]:
#resize()  ->  resize() changes the shape of an array and can also change the number of elements.

#Method 1: resize() as an Array Method
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(2, 3)
print(arr)

#Changing to a Larger Size
arr = np.array([1, 2, 3, 4])
arr.resize(2, 3)
print(arr)

#Changing to a Smaller Size
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(2, 2)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 0 0]]
[[1 2]
 [3 4]]


**Transpose and Dimensions**

This topic focuses on changing the arrangement or number of dimensions of an array.

In [ ]:
#Transpose Using .T  -> Transpose changes rows into columns and columns into rows.

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr)
print(arr.shape)
transposed = arr.T  #using .T
print(transposed)
print(transposed.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [29]:
#transpose() ->  np.transpose() performs the same basic operation.
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
result = np.transpose(arr)
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
#  Transpose for 3D Arrays
arr = np.zeros((2, 3, 4))

print(arr.shape)
print(arr.T.shape)

result = np.transpose(arr, (1, 0, 2))
print(result.shape)

(2, 3, 4)
(4, 3, 2)
(3, 2, 4)


In [31]:
# np.expand_dims() -> expand_dims() adds a new dimension of size 1.
arr = np.array([10, 20, 30])
print(arr.shape)

result = np.expand_dims(arr, axis=0)
print(result)
print(result.shape)

# Add a Dimension at Axis 1
result = np.expand_dims(arr, axis=1)
print(result)
print(result.shape)

(3,)
[[10 20 30]]
(1, 3)
[[10]
 [20]
 [30]]
(3, 1)


In [32]:
#np.squeeze()  ->  squeeze() removes dimensions whose size is 1.
arr = np.array([[
    10, 20, 30
]])
print(arr.shape)

result = np.squeeze(arr)
print(result)
print(result.shape)

(1, 3)
[10 20 30]
(3,)


**Combining and Splitting Arrays**

These operations are used to join multiple arrays together or divide one array into smaller arrays. They are useful when preparing datasets, combining features, and dividing data into batches.

In [34]:
# np.concatenate()  -> concatenate() joins arrays along an existing axis.

#Combining 1D Arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.concatenate((a, b))
print(result)

#Combining 2D Arrays Along Rows
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])
result = np.concatenate((a, b), axis=0)
print(result)

#Combining 2D Arrays Along Columns
result = np.concatenate((a, b), axis=1)

print(result)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [37]:
# np.vstack()  -> vstack() means vertical stacking. It places arrays one below another.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

#2D
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])
print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
# np.hstack() -> hstack() means horizontal stacking. It places arrays side by side.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)

# 2D arrays:
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])
print(np.hstack((a, b)))

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [39]:
#np.split() -> split() divides an array into equal-sized sections.

#Splitting a 1D Array
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)
print(result)

# Accessing a Split Part
parts = np.split(arr, 3)
print(parts[0])
print(parts[1])

# Splitting a 2D Array by Rows
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])
result = np.split(arr, 2, axis=0)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [40]:
#  np.array_split()  ->  array_split() is similar to split(), but it also allows unequal divisions.
# Unequal Splitting
arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]
