**Mathematical and Statistical Operations**

Goal: Perform numerical calculations efficiently using NumPy, without writing loops.

In [2]:
import numpy as np

**Aggregation Functions**

Aggregation functions summarize multiple values into a single value or a smaller set of values.

In [3]:
# sum() -> sum() calculates the total of all elements.
arr = np.array([10, 20, 30, 40, 50])
print(np.sum(arr))

150


In [4]:
#mean() -> mean() calculates the average.
# Mean = Number of values/Sum of values
arr = np.array([10, 20, 30, 40, 50])
print(np.mean(arr))

30.0


In [5]:
# min() and max()

#min() returns the smallest value.
print(np.min(arr))

#max() returns the largest value.
print(np.max(arr))

10
50


In [6]:
# std() -> std() calculates the standard deviation, which measures how spread out values are from the mean.
#Small standard deviation: Values are close to the mean.
#Large standard deviation: Values are more spread out.

arr = np.array([10, 20, 30, 40, 50])
print(np.std(arr))

14.142135623730951


In [7]:
# var() -> var() calculates the variance.
#Variance is related to standard deviation:
#Variance = Standard Deviation^2

print(np.var(arr))

200.0


In [8]:
# median() -> The median is the middle value after sorting the data.

arr = np.array([10, 50, 20, 40, 30])
print(np.median(arr))

30.0


**Axis Concept**

The axis parameter tells NumPy along which direction an operation should be performed.

For a 2D array:

-> axis=0 works down the rows, producing one result for each column.

-> axis=1 works across the columns, producing one result for each row.

In [9]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [11]:
# axis=0: Column-wise Operation
# When you use axis=0, NumPy combines values vertically, down each column.

#Sum of Each Column
print(np.sum(arr, axis=0))

#Mean of Each Column
print(np.mean(arr, axis=0))

#Minimum of Each Column
print(np.min(arr, axis=0))

[120 150 180]
[40. 50. 60.]
[10 20 30]


In [12]:
# axis=1: Row-wise Operation
# When you use axis=1, NumPy combines values horizontally, across each row.

#Sum of Each Row
print(np.sum(arr, axis=1))

#Mean of Each Row
print(np.mean(arr, axis=1))

[ 60 150 240]
[20. 50. 80.]


In [16]:
# axis=None -> The default behavior is usually axis=None, which performs the operation over all elements.
print(np.sum(arr))
print(np.sum(arr, axis=None))

450
450


In [17]:
# Shape of Results
# For an array with shape (3, 3):
np.sum(arr, axis=0).shape
np.sum(arr, axis=1).shape

(3,)

**Finding Positions and Values**

NumPy provides functions to find:

- The position of the smallest value

- The position of the largest value

- The positions where a condition is true

- The number of non-zero values

In [19]:
#argmin() -> argmin() returns the index of the smallest value.
arr = np.array([40, 10, 70, 20, 90])
print(np.argmin(arr))

#To get the smallest value itself:
print(arr[np.argmin(arr)])

# argmin() with a 2D Array
arr = np.array([
    [40, 10, 70],
    [20, 90, 30]
])
print(np.argmin(arr))

#With axis
print(np.argmin(arr, axis=0))

1
10
1
[1 0 1]


In [20]:
#argmax() -> argmax() returns the index of the largest value.
arr = np.array([40, 10, 70, 20, 90])
print(np.argmax(arr))

#To get the largest value:
print(arr[np.argmax(arr)])

#With a 2D Array
arr = np.array([
    [40, 10, 70],
    [20, 90, 30]
])
print(np.argmax(arr, axis=0))

#This finds the index of the maximum value in each column.
print(np.argmax(arr, axis=1))

4
90
[0 1 0]
[2 1]


In [22]:
# np.where() -> np.where() finds the indices where a condition is true.

#Find Positions of Values Greater Than 30
arr = np.array([10, 40, 20, 60, 30, 80])
print(np.where(arr > 30))

#To get a simple index array:
indices = np.where(arr > 30)[0]
print(indices)

#Find Positions of Even Numbers
arr = np.array([11, 12, 13, 14, 15, 16])
print(np.where(arr % 2 == 0)[0])

# np.where() for Conditional Replacement
# np.where() can also return values depending on a condition.
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 25, 1, 0)
print(result)

(array([1, 3, 5]),)
[1 3 5]
[1 3 5]
[0 0 1 1 1]


In [23]:
#count_nonzero() -> count_nonzero() counts the number of elements that are not zero.
arr = np.array([0, 10, 0, 20, 30, 0])
print(np.count_nonzero(arr))

#Count Non-Zero Values in a 2D Array
arr = np.array([
    [1, 0, 3],
    [0, 0, 6],
    [7, 8, 0]
])
print(np.count_nonzero(arr))

#With axis=0
print(np.count_nonzero(arr, axis=0))

#With axis=1
print(np.count_nonzero(arr, axis=1))

3
5
[2 1 2]
[2 1 2]


**Rounding and Absolute Values**

NumPy provides functions to modify decimal values, calculate absolute values, and round numbers.

In [24]:
# np.abs() — Absolute Value
#Returns the non-negative value of each element.
arr = np.array([-10, -5.5, 0, 4.2, 8])
print(np.abs(arr))

[10.   5.5  0.   4.2  8. ]


In [26]:
#np.round() — Round Values
#Rounds values to the nearest number.
arr = np.array([2.3, 4.6, 7.8, 9.1])
print(np.round(arr))

#Rounding to Specific Decimal Places. Use the decimals parameter.
arr = np.array([2.3456, 4.6789, 7.1234])
print(np.round(arr, decimals=2))

[2. 5. 8. 9.]
[2.35 4.68 7.12]


In [27]:
#np.floor() — Round Down
#Rounds each value toward negative infinity.
arr = np.array([2.3, 2.9, -2.3, -2.9])
print(np.floor(arr))

[ 2.  2. -3. -3.]


In [28]:
#np.ceil() — Round Up
#Rounds each value toward positive infinity.
arr = np.array([2.3, 2.9, -2.3, -2.9])
print(np.ceil(arr))

[ 3.  3. -2. -2.]


**Basic Mathematical Functions**

NumPy provides mathematical functions that operate on every element of an array.

In [29]:
# np.sqrt() — Square Root. Calculates the square root of each element.
arr = np.array([4, 9, 16, 25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


In [30]:
#np.power() — Power
#Raises each element to a specified power.
arr = np.array([2, 3, 4])
print(np.power(arr, 2))

[ 4  9 16]


In [31]:
#np.exp() — Exponential
#Calculates e^x, where e≈2.71828.
arr = np.array([0, 1, 2, 3])
print(np.exp(arr))

[ 1.          2.71828183  7.3890561  20.08553692]


In [32]:
#np.log() — Natural Logarithm
#Calculates the natural logarithm, using base e.
arr = np.array([1, np.e, np.e ** 2])
print(np.log(arr))

[0. 1. 2.]


In [33]:
#np.log10() — Base-10 Logarithm
#Calculates logarithm with base 10.
arr = np.array([1, 10, 100, 1000])
print(np.log10(arr))

[0. 1. 2. 3.]


In [35]:
#np.log2() — Base-2 Logarithm
#Calculates logarithm with base 2.
arr = np.array([1, 2, 4, 8, 16])
print(np.log2(arr))

[0. 1. 2. 3. 4.]


**Sorting and Unique Values**

These functions are useful for organizing data, finding rankings, and removing duplicate values.

In [37]:
# np.sort() — Sort Values
# Returns a sorted copy of an array. The original array is not changed.
arr = np.array([40, 10, 30, 20])
sorted_arr = np.sort(arr)
print(sorted_arr)
print(arr)

#Sorting in Descending Order
#Use slicing with [::-1].
arr = np.array([40, 10, 30, 20])
print(np.sort(arr)[::-1])

[10 20 30 40]
[40 10 30 20]
[40 30 20 10]


In [38]:
#Sorting a 2D Array
#By default, sorting is performed along the last axis, which means each row for a 2D array.
arr = np.array([
    [30, 10, 20],
    [60, 40, 50]
])
print(np.sort(arr))

#Sort column-wise using axis=0:
print(np.sort(arr, axis=0))

[[10 20 30]
 [40 50 60]]
[[30 10 20]
 [60 40 50]]


In [39]:
#argsort() — Get Sorting Indices
#np.argsort() returns the indices that would sort the array.
arr = np.array([40, 10, 30, 20])
indices = np.argsort(arr)
print(indices)

[1 3 2 0]


In [40]:
#np.unique() — Find Unique Values
#Returns the distinct values in an array, removing duplicates.
arr = np.array([10, 20, 10, 30, 20, 40, 30])
print(np.unique(arr))

[10 20 30 40]


In [41]:
#Get Counts of Unique Values
#Use return_counts=True.
arr = np.array(["Java", "Python", "Java", "C++", "Python", "Java"])
values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)

['C++' 'Java' 'Python']
[1 3 2]


In [42]:
#Get First Occurrence Indices
#Use return_index=True.
arr = np.array([30, 10, 20, 10, 30])
values, indices = np.unique(arr, return_index=True)
print(values)
print(indices)

[10 20 30]
[1 2 0]
