**What Is Vectorization?**

Vectorization means applying an operation to an entire NumPy array without explicitly writing a Python loop.

In [1]:
# Using a Python Loop
numbers = [1, 2, 3, 4, 5]
squared = []
for num in numbers:
    squared.append(num ** 2)
print(squared)

[1, 4, 9, 16, 25]


In [3]:
# Using Vectorization
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
squared = numbers ** 2
print(squared)

arr = np.array([10, 20, 30, 40])
print(arr + 5)
print(arr * 2)
print(arr / 10)
print(arr ** 2)

[ 1  4  9 16 25]
[15 25 35 45]
[20 40 60 80]
[1. 2. 3. 4.]
[ 100  400  900 1600]


**Why Vectorization Is Preferred**

- Faster for large numerical arrays

- Uses optimized low-level operations

- Requires less code

- Reduces explicit Python loops

- Commonly used in ML operations involving data, weights, images, and matrices

Vectorization means using NumPy’s array operations to process multiple values together.

**Broadcasting Rules**

Broadcasting allows NumPy to perform operations on arrays with different shapes.

In [4]:
# Rule 1: Same-Shape Arrays
#Arrays with identical shapes can be operated element-wise.
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)

# Rule 2: Scalar Broadcasting
#A scalar can be used with an array of any shape.
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(matrix + 10)

# Rule 3: 1D Array with a 2D Array
#Consider a matrix with shape (2, 3):
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
row = np.array([1, 2, 3])
print(matrix.shape)
print(row.shape)
# Now add them:
print(matrix + row)
#The 1D array is broadcast across every row.


# Rule 4: Column Vector with a Matrix
#A column vector has shape (2, 1).
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
column = np.array([
    [1],
    [2]
])
print(matrix.shape)
print(column.shape)
#Add them:
print(matrix + column)

[11 22 33]
[[11 12 13]
 [14 15 16]]
(2, 3)
(3,)
[[11 22 33]
 [41 52 63]]
(2, 3)
(2, 1)
[[11 21 31]
 [42 52 62]]


In [ ]:
# Incompatible Shapes
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([10, 20])
print(a + b)
#The dimensions 3 and 2 do not match, and neither is 1. Therefore, NumPy raises a broadcasting error.

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

**Practical Broadcasting**

In [6]:
# A. Adding a Row Vector to a Matrix
X = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
bias = np.array([1, 2, 3])
result = X + bias
print(result)


# B. Subtracting Column Means
#Suppose each row represents a student and each column represents a subject.
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
mean = X.mean(axis=0)
print(mean)


#C. Normalizing an Array
#Normalization scales values into a common range, often from 0 to 1.
# Min-Max Normalization
# Formula: X normalized=(X-Xmin)/(Xmax-Xmin)
X = np.array([10, 20, 30, 40, 50])
X_min = X.min()
X_max = X.max()
normalized = (X - X_min) / (X_max - X_min)
print(normalized)


# D. Standardization
#Standardization transforms values so that they have:
#Mean approximately 0
#Standard deviation approximately 1
# Formula: Xstanardzed=(X-μ​)/σ
X = np.array([10, 20, 30, 40, 50])
mean = X.mean()
std = X.std()
standardized = (X - mean) / std
print(standardized)


# E. Row-Wise Normalization in a Matrix
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
row_sums = X.sum(axis=1, keepdims=True)
normalized_rows = X / row_sums
print(normalized_rows)

[[11 22 33]
 [41 52 63]]
[40. 50. 60.]
[0.   0.25 0.5  0.75 1.  ]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]]


**Universal Functions — ufuncs**

Universal functions, or ufuncs, are NumPy functions that operate element-wise on arrays.

In [7]:
# A. Arithmetic ufuncs

# np.add()
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(np.add(a, b))


#np.subtract()
print(np.subtract(a, b))

#np.multiply()
print(np.multiply(a, b))


#np.divide()
print(np.divide(a, b))

#other common ufuncs
print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))
print(np.log(arr))

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[3.16227766 4.47213595 5.47722558 6.32455532]
[ 100  400  900 1600]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]
[2.30258509 2.99573227 3.40119738 3.68887945]


In [8]:
#B. np.maximum()
#Compares corresponding elements and returns the larger value.
a = np.array([10, 25, 30])
b = np.array([15, 20, 35])
print(np.maximum(a, b))

#Practical Example: ReLU
#The ReLU activation function is:
#ReLU(x)=max(0,x)
x = np.array([-3, -1, 0, 2, 5])
relu = np.maximum(0, x)
print(relu)

[15 25 35]
[0 0 0 2 5]


In [ ]:
#C. np.minimum()
#Compares corresponding elements and returns the smaller value.
a = np.array([10, 25, 30])
b = np.array([15, 20, 35])
print(np.minimum(a, b))

[10 20 30]


In [11]:
#Clipping Values
#np.clip() restricts values to a specified minimum and maximum.
arr = np.array([-10, 5, 15, 25, 40])
result = np.clip(arr, 0, 30)
print(result)

[ 0  5 15 25 30]


In [12]:
# E. Comparison and Logical ufuncs
#NumPy provides functions for comparing array values and combining conditions.

#1. np.greater()
#Checks whether each element in the first array is greater than the corresponding element in the second array.
a = np.array([10, 20, 30])
b = np.array([5, 25, 30])
print(np.greater(a, b))

#2. np.less()
#Checks whether elements are smaller.
print(np.less(a, b))

#3. np.equal()
#Checks whether corresponding elements are equal.
print(np.equal(a, b))

#4. np.logical_and()
#Returns True only when both conditions are True.
arr = np.array([10, 20, 30, 40, 50])
condition = np.logical_and(arr >= 20, arr <= 40)
print(condition)
print(arr[condition])

#5. np.logical_or()
#Returns True when at least one condition is True.
arr = np.array([10, 20, 30, 40, 50])
condition = np.logical_or(arr < 20, arr > 40)
print(arr[condition])

# np.logical_not()
#Reverses Boolean values.
condition = np.array([True, False, True])
print(np.logical_not(condition))

[ True False False]
[False  True False]
[False False  True]
[False  True  True  True False]
[20 30 40]
[10 50]
[False  True False]


In [13]:
#F. Conditional Selection with np.where()
#np.where() selects values based on a condition.
marks = np.array([35, 45, 60, 25, 80])
result = np.where(marks >= 40, "Pass", "Fail")
print(result)

#Example: Replace Negative Values
arr = np.array([-5, 10, -2, 8, -1])
result = np.where(arr < 0, 0, arr)
print(result)

['Fail' 'Pass' 'Pass' 'Fail' 'Pass']
[ 0 10  0  8  0]
