**Linear Algebra**

Goal: Learn the NumPy operations commonly used in Machine Learning, Deep Learning, and mathematical computing.

Linear algebra deals with vectors, matrices, matrix multiplication, distances, transformations, and systems of equations.

**Matrix and Vector Concepts**

In [3]:
# A. Vector -> A vector is a one-dimensional array.
import numpy as np
v = np.array([10, 20, 30])
print(v)
print(v.shape)
print(v.ndim)

# B. Matrix -> A matrix is a two-dimensional array containing rows and columns.
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(A.shape)
print(A.ndim)

#C. Matrix Dimensions
#For a matrix with shape (m, n):
#m = number of rows
#n = number of columns
#Example:
#A → shape (2, 3)
#     2 rows
#     3 columns

[10 20 30]
(3,)
1
[[1 2 3]
 [4 5 6]]
(2, 3)
2


**Matrix Multiplication**

Matrix multiplication is one of the most important operations in ML and neural networks.

NumPy provides:

- np.dot()

- @ operator

In [6]:
#A. Using the @ Operator
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
C = A @ B
print(C)


#B. Using np.dot()
C = np.dot(A, B)
print(C)


#C. Matrix Multiplication Shape Rule
'''For matrix multiplication:
A shape = (m, n)
B shape = (n, p)
Result shape = (m, p)
The inner dimensions must match.
Example:
A → (2, 3)
B → (3, 4)
Result → (2, 4)'''

#Valid example:
A = np.ones((2, 3))
B = np.ones((3, 4))
print((A @ B).shape)

#Invalid example:
A = np.ones((2, 3))
B = np.ones((2, 4))
#print(A @ B)
#This raises an error because the inner dimensions 3 and 2 do not match.


#D. Element-Wise Multiplication vs Matrix Multiplication
#This distinction is essential.
#Element-Wise Multiplication: *
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
print(A * B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
(2, 4)
[[ 5 12]
 [21 32]]


**Dot Product**

The dot product of two vectors multiplies corresponding elements and adds the results.

a⋅b=i∑(ai)(bi)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.dot(a, b)
print(result)

#Using @ also works for vectors:
print(a @ b)

32
32


In [10]:
#ML Application
#A linear model often calculates:
#   y=w⋅x+b
x = np.array([2, 3, 4])
w = np.array([0.5, 1.0, 1.5])
bias = 2
y = w @ x + bias
print(y)

12.0


**Transpose**

Transpose changes rows into columns and columns into rows.

In [12]:
#A. Using .T
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(A.T)


#B. Using np.transpose()
print(np.transpose(A))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


**np.linalg.norm() — Vector and Matrix Norm**

A norm measures the magnitude or length of a vector or matrix.

In [13]:
#A. Vector Norm
#For a vector, the default norm is the Euclidean length:
#||v||2=sqrt((x1^2)+(x2^2)+.....(xn^2))
v = np.array([3, 4])
print(np.linalg.norm(v))


#B. Matrix Norm
A = np.array([
    [1, 2],
    [3, 4]
])
print(np.linalg.norm(A))


#C. Other Norms
#1. L1 Norm
#The L1 norm is the sum of absolute values.
v = np.array([-3, 4, -5])
print(np.linalg.norm(v, ord=1))
#2. L2 Norm
print(np.linalg.norm(v, ord=2))

5.0
5.477225575051661
12.0
7.0710678118654755


**np.linalg.inv() — Matrix Inverse**
The inverse of a square matrix A is written as A−1.

It satisfies:AA^−1=I

In [14]:
#where I is the identity matrix.
A = np.array([
    [4, 7],
    [2, 6]
])
A_inv = np.linalg.inv(A)
print(A_inv)


'''Limitations of np.linalg.inv()
The inverse exists only when:
The matrix is square.
The matrix is non-singular.
Its determinant is not zero.'''

#Example of a singular matrix:
A = np.array([
    [1, 2],
    [2, 4]
])
print(np.linalg.det(A))

[[ 0.6 -0.7]
 [-0.2  0.4]]
0.0


**np.linalg.det() — Determinant**

The determinant is a scalar value calculated from a square matrix.

In [15]:
A = np.array([
    [4, 7],
    [2, 6]
])

print(np.linalg.det(A))

10.000000000000002


**np.linalg.solve() — Solve Linear Equations**

np.linalg.solve() solves a system of linear equations:

Ax=b

Instead of calculating:

x=A−1b

use np.linalg.solve(A, b).

In [16]:
'''Example
Consider the equations:
2x+y=5
x+3y=6'''
A = np.array([
    [2, 1],
    [1, 3]
])
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(x)

[1.8 1.4]


**Eigenvalues and Eigenvectors**

Eigenvalues and eigenvectors describe special directions and scaling behavior of a matrix.

The relationship is:

Av=λv

where:

- A = matrix

- v = eigenvector

- λ = eigenvalue

This means that multiplying a matrix by an eigenvector changes its magnitude but not its direction.

In [18]:
#Using np.linalg.eig()
A = np.array([
    [2, 0],
    [0, 3]
])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 3.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]
