**Random Numbers and Data Generation**

Goal: Generate random data for machine learning, experiments, initialization, and sampling.

NumPy’s modern random-number API uses np.random.default_rng() to create a Generator object.

**Creating a Random Number Generator**

In [2]:
#Modern approach
import numpy as np
rng = np.random.default_rng(42)

'''
Here:
np.random is NumPy’s random module.
default_rng() creates a modern random number generator.
42 is the seed.
rng is used to generate random values.

Why use Generator?
The modern Generator API is recommended because it:
Provides better random-number generation methods.
Supports independent random streams.
Makes code easier to control and reproduce.
Avoids relying on global random state.'''

#Older style:
np.random.seed(42)
np.random.rand(3)

#Modern style:
rng = np.random.default_rng(42)
rng.random(3)

array([0.77395605, 0.43887844, 0.85859792])

**Random Number Generation**

In [4]:
#Random Floating-Point Numbers
#The random() method generates values between 0 and 1.
rng = np.random.default_rng(42)
x = rng.random(5)
print(x)


#Generate a matrix
X = rng.random((3, 4))
print(X)

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[[0.97562235 0.7611397  0.78606431 0.12811363]
 [0.45038594 0.37079802 0.92676499 0.64386512]
 [0.82276161 0.4434142  0.22723872 0.55458479]]


**Uniform Distribution**

A uniform distribution generates values where every value in a specified interval has equal probability.

In [5]:
rng = np.random.default_rng(42)
x = rng.uniform(10, 20, size=5)
print(x)

#Generate 2D data
X = rng.uniform(0, 100, size=(3, 2))
print(X)

[17.73956049 14.3887844  18.5859792  16.97368029 10.94177348]
[[97.56223516 76.1139702 ]
 [78.60643053 12.81136327]
 [45.03859379 37.07980242]]


**Normal Distribution**

A normal distribution, also called a Gaussian distribution, is centered around a mean.

In [6]:
'''
Where:
loc = mean
scale = standard deviation
size = output shape"
'''
rng = np.random.default_rng(42)
x = rng.normal(loc=0, scale=1, size=5)
print(x)

#Generate data with a different mean and standard deviation
x = rng.normal(loc=50, scale=10, size=1000)
print("Mean:", x.mean())
print("Standard deviation:", x.std())


#Generate a feature matrix
X = rng.normal(loc=0, scale=1, size=(100, 3))

print(X.shape)

[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519]
Mean: 49.715375963276934
Standard deviation: 9.860409351256388
(100, 3)


**Random Integers**

Use rng.integers() to generate random integer values.

In [7]:
rng = np.random.default_rng(42)
x = rng.integers(1, 10, size=5)
print(x)

#Generate a matrix of integers
X = rng.integers(0, 100, size=(3, 4))
print(X)

#Generate random labels
labels = rng.integers(0, 3, size=10)
print(labels)

[1 7 6 4 4]
[[85  8 69 20]
 [ 9 52 97 73]
 [76 71 78 51]]
[0 2 1 1 1 0 2 2 1 1]


**Random Sampling with choice()**

The choice() method selects random elements from an array or range.

rng.choice(array, size=None, replace=True)

Parameters:

- array: Source values.

- size: Number of elements to select.

- replace=True: Allows repeated selection.

- replace=False: Prevents repeated selection.

In [8]:
#Sampling with Replacement
#Sampling with replacement means an item can be selected more than once.
rng = np.random.default_rng(42)
data = np.array([10, 20, 30, 40, 50])
sample = rng.choice(data, size=8, replace=True)
print(sample)

sample = rng.choice(10, size=5, replace=True)
print(sample)

[10 40 40 30 30 50 10 40]
[2 0 5 9 7]


In [10]:
#Sampling without Replacement
#Sampling without replacement means an item cannot be selected more than once.
data = np.array([10, 20, 30, 40, 50])
sample = rng.choice(data, size=3, replace=False)
print(sample)
# This causes an error:
#rng.choice(data, size=10, replace=False)

[50 30 20]


In [11]:
#Sampling with Probabilities
#You can assign a probability to each item using p.
data = np.array(["A", "B", "C"])
sample = rng.choice(data,size=10,replace=True,p=[0.7, 0.2, 0.1])
print(sample)

['A' 'B' 'A' 'A' 'A' 'A' 'B' 'A' 'B' 'A']


**Reproducibility with Random Seeds**

Random operations normally produce different results each time.

A random seed makes the generated sequence repeatable.

In [12]:
#The same seed produces the same sequence.
rng1 = np.random.default_rng(42)
rng2 = np.random.default_rng(42)
print(rng1.random(5))
print(rng2.random(5))

#Different seeds produce different results
rng1 = np.random.default_rng(42)
rng2 = np.random.default_rng(100)
print(rng1.random(3))
print(rng2.random(3))

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[0.77395605 0.43887844 0.85859792]
[0.83498163 0.59655403 0.28886324]


**Shuffling Data with shuffle()**

The shuffle() method randomly rearranges an array in place.

In [ ]:
rng = np.random.default_rng(42)
data = np.array([1, 2, 3, 4, 5])
rng.shuffle(data)
print(data)  #original data is modified

[5 3 4 2 1]


In [14]:
#Shuffling a 2D Array
#For a 2D array, shuffle() shuffles along the first axis by default. This means it rearranges rows.
rng = np.random.default_rng(42)
X = np.array([[1, 10],[2, 20],[3, 30],[4, 40]])
rng.shuffle(X)
print(X)

[[ 4 40]
 [ 3 30]
 [ 2 20]
 [ 1 10]]


**Shuffling with permutation()**

The permutation() method returns a shuffled copy instead of modifying the original array.

In [16]:
#example
rng = np.random.default_rng(42)
data = np.array([1, 2, 3, 4, 5])
shuffled = rng.permutation(data)
print("Original:", data)
print("Shuffled:", shuffled)

#Permutation of an Integer Range
rng = np.random.default_rng(42)
indices = rng.permutation(10)
print(indices)

Original: [1 2 3 4 5]
Shuffled: [5 3 4 2 1]
[5 6 0 7 3 2 4 9 1 8]


In [18]:
#Common ML use: Shuffle indices
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
])

y = np.array([0, 1, 0, 1])

rng = np.random.default_rng(42)

indices = rng.permutation(len(X))

X_shuffled = X[indices]
y_shuffled = y[indices]

print(X_shuffled)
print(y_shuffled)

[[ 40 400]
 [ 30 300]
 [ 20 200]
 [ 10 100]]
[1 0 1 0]
