**Handling Missing Values and Data Cleaning**

Goal: Use NumPy for basic numerical data cleaning before working with Pandas or machine-learning models.

Data cleaning is the process of identifying and correcting invalid, missing, or extreme values in a dataset.

**NaN and Infinity**

NumPy provides special values to represent missing or invalid numerical data.

In [3]:
#np.nan
#np.nan means Not a Number. It is commonly used to represent missing numerical values.
import numpy as np
x = np.nan
print(x)
#with array
arr = np.array([10, 20, np.nan, 40])
print(arr)


#np.inf
#np.inf represents positive infinity.
x = np.inf
print(x)
#negative infinity
x = -np.inf 
print(x)
#array
arr = np.array([10, np.inf, -np.inf, 30])
print(arr)


nan
[10. 20. nan 40.]
inf
-inf
[ 10.  inf -inf  30.]


**Detecting NaN Values with np.isnan()**

In [5]:
#np.isnan() checks whether each value is NaN.
arr = np.array([10, np.nan, 30, np.nan])
result = np.isnan(arr)
print(result)

#count missing values
missing_count = np.isnan(arr).sum()
print(missing_count)

#Check whether any NaN exists
print(np.isnan(arr).any())

#Check whether all values are NaN
print(np.isnan(arr).all())



[False  True False  True]
2
True
False


**Detecting Infinity with np.isinf()**

In [6]:
#np.isinf() checks whether values are positive or negative infinity.
arr = np.array([10, np.inf, -np.inf, 30, np.nan])
result = np.isinf(arr)
print(result)

#Count infinite values:
print(np.isinf(arr).sum())

[False  True  True False False]
2


**Detecting Valid Values with np.isfinite()**

np.isfinite() returns True only for finite values.

It returns False for:

- np.nan
- np.inf
- -np.inf

In [7]:
arr = np.array([10, np.nan, np.inf, -np.inf, 30])
result = np.isfinite(arr)
print(result)

[ True False False False  True]


**Why Missing Values Matter**

Missing or invalid values can affect numerical calculations and machine-learning models.

**Problems caused by missing values**

- Mean and sum may become NaN.

- Statistical calculations may become invalid.

- ML models may fail to train.

- Normalization and standardization may produce incorrect results.

- Missing values can reduce model accuracy.

- Infinite values can cause overflow or unstable calculations.

In [9]:
#example
arr = np.array([10, 20, np.nan, 40])
print(np.mean(arr))

#To ignore NaN values during certain statistical operations, NumPy provides functions such as:
'''
np.nanmean()
np.nansum()
np.nanmin()
np.nanmax()
np.nanstd()
'''
#example
arr = np.array([10, 20, np.nan, 40])
print(np.nanmean(arr))

nan
23.333333333333332


**Handling Missing Values with np.nan_to_num()**

np.nan_to_num() replaces invalid numerical values with usable numbers.

It can replace:

- NaN

- Positive infinity

- Negative infinity

In [11]:
#Replace NaN with zero
arr = np.array([10, np.nan, 30, np.nan])
cleaned = np.nan_to_num(arr)
print(cleaned)

#Replace Positive and Negative Infinity
arr = np.array([10, np.inf, -np.inf, np.nan])
cleaned = np.nan_to_num(arr,nan=0,posinf=100,neginf=-100)
print(cleaned)

#Default Infinity Replacement
#If posinf and neginf are not specified, NumPy replaces infinity with very large finite values based on the array’s data type.
arr = np.array([np.inf, -np.inf])
cleaned = np.nan_to_num(arr)
print(cleaned)

[10.  0. 30.  0.]
[  10.  100. -100.    0.]
[ 1.79769313e+308 -1.79769313e+308]


**Important Limitation of Replacing NaN**

Replacing every missing value with zero is not always statistically correct.

For example:

- Missing age should not automatically mean age 0.

- Missing income should not automatically mean income 0.

- Missing temperature should not automatically mean 0°C.

Possible strategies include:

- Replacing with zero when zero has meaningful meaning.

- Replacing with the mean.

- Replacing with the median.

- Replacing with the most frequent value.

- Removing rows or columns.

- Using a model-based imputation method.

NumPy provides the basic numerical operations, while Pandas and scikit-learn provide more advanced missing-value handling tools.

**Replacing NaN Values Using np.where()**

np.where() performs conditional selection or replacement.

In [13]:
#Replace NaN with zero
arr = np.array([10, np.nan, 30, np.nan])
cleaned = np.where(np.isnan(arr), 0, arr)
print(cleaned)

#Replace Negative Values
arr = np.array([10, -5, 20, -3, 30])
cleaned = np.where(arr < 0, 0, arr)
print(cleaned)

[10.  0. 30.  0.]
[10  0 20  0 30]


**Conditional Selection with np.select()**

np.select() applies multiple conditions and assigns different values depending on which condition is true.

Parameters:

- conditions: List of Boolean conditions.

- choices: Values corresponding to each condition.

- default: Value used when no condition is true.

In [14]:
#example
arr = np.array([-5, 0, 10, 25, 50])
conditions = [arr < 0,arr == 0,arr > 20]
choices = [0,1,2]
result = np.select(conditions, choices, default=3)
print(result)

#Condition priority
#If more than one condition is true, np.select() uses the first matching condition.
arr = np.array([5, 15, 25])
conditions = [arr > 10,arr > 20]
choices = [1, 2]
result = np.select(conditions, choices, default=0)
print(result)

[0 1 3 2 2]
[0 1 1]


**Clipping Values with np.clip()**

np.clip() limits values to a specified minimum and maximum range.

Values are handled as follows:

- Values below the minimum become the minimum.

- Values above the maximum become the maximum.

- Values inside the range remain unchanged.

Rules:

- -10 becomes 0.

- 30 becomes 20.

- Values between 0 and 20 remain unchanged.

In [15]:
#example
arr = np.array([-10, 0, 5, 10, 20, 30])
clipped = np.clip(arr, 0, 20)
print(clipped)


#Clipping Outliers
#Outliers are values that are unusually high or low compared with the rest of the data.
arr = np.array([10, 12, 15, 18, 1000])
clipped = np.clip(arr, 0, 100)
print(clipped)

#Clipping Image Pixel Values
#Image pixel values are commonly expected to be in the range 0 to 255.
pixels = np.array([-20, 0, 100, 255, 300])
cleaned_pixels = np.clip(pixels, 0, 255)
print(cleaned_pixels)

#Clipping with Different Bounds
#The minimum and maximum can also be arrays, allowing different limits for different elements.
arr = np.array([10, 50, 100])
minimum = np.array([0, 20, 80])
maximum = np.array([20, 60, 90])
result = np.clip(arr, minimum, maximum)
print(result)

[ 0  0  5 10 20 20]
[ 10  12  15  18 100]
[  0   0 100 255 255]
[10 50 90]


**Combined Data-Cleaning Workflow**

A basic NumPy cleaning process can follow this order:

Identify invalid values

Detect NaN and infinity

Replace or remove invalid values

Apply conditional rules

Clip extreme values

Use cleaned data for analysis or ML