**Advanced Reshaping**

In [1]:
# reshape(-1, 1) -> This converts a 1D array into a column vector.
# -1 tells NumPy to automatically calculate that dimension.
import numpy as np
x = np.array([10, 20, 30, 40])
x_col = x.reshape(-1, 1)
print(x_col)
print(x_col.shape)

[[10]
 [20]
 [30]
 [40]]
(4, 1)


In [2]:
#reshape(1, -1)
#This converts a 1D array into a row vector.
x = np.array([10, 20, 30, 40])
x_row = x.reshape(1, -1)
print(x_row)
print(x_row.shape)

[[10 20 30 40]]
(1, 4)


**Singleton Dimensions**

A dimension whose size is 1 is called a singleton dimension.

In [4]:
x = np.array([10, 20, 30])
print(x.shape)

#adding dimension
x = x.reshape(-1, 1)
print(x.shape)

(3,)
(3, 1)


**Stacking and Concatenation**

The key concept is axis.

In [5]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

#concatenate()
#axis=0 -> combinig along row
result = np.concatenate((A, B), axis=0)
print(result)
print(result.shape)

#axis=1 -> Combine along columns.
result = np.concatenate((A, B), axis=1)
print(result)
print(result.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


**vstack() and hstack()**

In [ ]:
#vstack() -> Vertical stacking:
result = np.vstack((A, B))
print(result)
np.concatenate((A, B), axis=0)  #equivalent to above

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
#hstack() -> Horizontal stacking:
result = np.hstack((A, B))
print(result)
np.concatenate((A, B), axis=1)  #equivalent to

[[1 2 5 6]
 [3 4 7 8]]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**Combining Batches of Data**

In [ ]:
batch1 = np.random.default_rng(42).normal(size=(32, 3))
batch2 = np.random.default_rng(43).normal(size=(16, 3))
combined = np.concatenate((batch1, batch2), axis=0)
print(combined.shape)  #(batch_size, features)

(48, 3)


**Advanced Indexing**

In [10]:
# Integer Array Indexing -> Multiple positions can be selected simultaneously.
x = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])
print(x[indices])

# 2D Integer Indexing
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
rows = np.array([0, 1, 2])
cols = np.array([2, 0, 1])
print(A[rows, cols])


[10 30 50]
[30 40 80]


**Boolean Masks**

A Boolean mask selects elements based on a condition.

In [11]:
x = np.array([10, 25, 5, 40, 15])
mask = x > 20
print(mask)

[False  True False  True False]


**Combining Boolean and Integer Indexing**

In [12]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [15, 25, 35]
])
rows = X[:, 0] > 30
result = X[rows][:, [0, 2]]
print(result)

[[40 60]
 [70 90]]


**Broadcasting with Higher Dimensions**

Higher-dimensional arrays are common in machine learning and deep learning.

A 3D array can represent:

(batch, height, width)

For image data with color channels, a common representation is:

(batch, height, width, channels)

For example:

(32, 224, 224, 3)

means:

32 images,224 pixels high,224 pixels wide,3 color channels

In [ ]:
#Broadcasting in 3D
X = np.zeros((2, 3, 4))
mean = np.array([1, 2, 3, 4])
result = X + mean
print(result.shape)

(2, 3, 4)


**Batch, Height, Width, Channel**

In [14]:
images = np.zeros((32, 224, 224, 3))
print(images.shape)

(32, 224, 224, 3)


**np.einsum()**

np.einsum() stands for Einstein summation.

It provides a compact way to express operations involving:

- Multiplication
- Summation
- Dot products
- Matrix multiplication
- Tensor operations
- Axis manipulation

In [15]:
#Vector Dot Product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,i->', a, b)
print(result)

32


**Matrix Multiplication with einsum()**

In [16]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
#standard multiplication
C = A @ B
#Using einsum():
C = np.einsum('ik,kj->ij', A, B)
print(C)


[[19 22]
 [43 50]]


**np.meshgrid()**

meshgrid() creates coordinate grids from coordinate arrays.

It is commonly used for:

- Mathematical functions
- Surface plots
- Contour plots
- Visualization
- Evaluating functions over a 2D grid

In [18]:
x = np.array([1, 2, 3])
y = np.array([10, 20])
X, Y = np.meshgrid(x, y)
print(X)
print(Y)
print(X.shape)
print(Y.shape)

#Using the Grid in a Function
Z = X**2 + Y**2
print(Z)

[[1 2 3]
 [1 2 3]]
[[10 10 10]
 [20 20 20]]
(2, 3)
(2, 3)
[[101 104 109]
 [401 404 409]]


**np.tile()**

tile() repeats an entire array a specified number of times.


In [19]:
#1D array
x = np.array([1, 2, 3])
result = np.tile(x, 3)
print(result)

#For 2D arrays:
x = np.array([
    [1, 2],
    [3, 4]
])
result = np.tile(x, (2, 3))
print(result)

[1 2 3 1 2 3 1 2 3]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


**np.repeat()**

repeat() repeats individual elements.

In [20]:
x = np.array([1, 2, 3])
result = np.repeat(x, 3)
print(result)

#For 2D arrays, you can specify an axis:
x = np.array([
    [1, 2],
    [3, 4]
])
result = np.repeat(x, 2, axis=0)
print(result)

[1 1 1 2 2 2 3 3 3]
[[1 2]
 [1 2]
 [3 4]
 [3 4]]


**Sliding Windows**

Sliding windows are useful when working with sequential data.

In [23]:
#It creates overlapping windows from an array.
x = np.array([1, 2, 3, 4, 5])
windows = np.lib.stride_tricks.sliding_window_view(x, window_shape=3)
print(windows)


#Sliding Windows for Time Series
data = np.array([10, 20, 30, 40, 50, 60])
windows = np.lib.stride_tricks.sliding_window_view(data, window_shape=3)
print(windows)


#Sliding Windows with 2D Arrays
image = np.arange(16).reshape(4, 4)
print(image)
windows = np.lib.stride_tricks.sliding_window_view(image,(2, 2))
print(windows.shape)

[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(3, 3, 2, 2)
